server:
  port: 8081

security:
  jwt:
    secret: QCyNB5+K56YTzblZMbUVrQED3twWo/mm1LcAic+Y/DB3NwaaGNSpFcC5Ef0/pNyoiUjX3hHQFhX09iKYc8AKqQ==
    access-token-expiration: 60

spring:
  application:
    name: owlet-service

  datasource:
    url: jdbc:postgresql://localhost:5432/owlet
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    #hibernate:
     # ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        #default_schema: school
  #        generate_statistics: true

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog-master.xml
    default-schema: public

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
#    org.springframework.security: DEBUG



springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true

  default-produces-media-type: application/json
